CREATE TABLE [dbo].[StudentLogin]
(
	[Id] INT NOT NULL PRIMARY KEY IDENTITY(100, 1),
	[UserName]             NVARCHAR (256) NOT NULL,
    [NormalizedUserName]   NVARCHAR (256) NOT NULL,
    [Email]                NVARCHAR (256) NULL,
    [NormalizedEmail]      NVARCHAR (256) NULL,
    [EmailConfirmed]       BIT            NOT NULL,
    [PasswordHash]         NVARCHAR (1000) NULL,
    [PhoneNumber]          NVARCHAR (50)  NULL,
    [PhoneNumberConfirmed] BIT            NOT NULL,
    [TwoFactorEnabled]     BIT            NOT NULL,
    [LockoutEndDate]       DATETIME NULL,
    [LockoutEnabled]       BIT                NOT NULL,
    [AccessFailedCount]    INT                NOT NULL,
    [SecurityStamp]        NVARCHAR (1000)     NULL, 
    [Password] NVARCHAR(50) NULL, 
    [IsLogin] BIT NULL,
    [LastLoginIP] NVARCHAR(50) NULL, 
    [LastLoginDate] DATETIME NULL, 
    [LastLoginDevice] NVARCHAR(500) NULL,
    [LastLoginLocation] NVARCHAR(500) NULL,
    [IsActive] BIT NULL DEFAULT 0, 
    [IsDelete] BIT NULL DEFAULT 0, 
    [ModifyDate] DATETIME NULL DEFAULT GetDate(), 
    [ModifyBy] INT NULL, 
    [AddedDate] DATETIME NULL DEFAULT GetDate(), 
    [AddedBy] INT NULL,
)
