CREATE TABLE [dbo].[StudentAdmission]
(
	[Id] INT NOT NULL PRIMARY KEY IDENTITY(100, 1), 
	[Sr_RegNo] NVARCHAR(80) NOT NULL,
	[AcademicSessionId] INT NOT NULL,
	[ClassId] INT NOT NULL,  
	[SectionId] INT NOT NULL,  
	[StudentLoginId] INT NOT NULL,
	[AdmissionDate] DATETIME NOT NULL, 
	[FirstName] NVARCHAR(50) NOT NULL, 
	[LastName] NVARCHAR(50) NOT NULL, 
	[FatherName] NVARCHAR(50) NOT NULL,
	[MobileNo] NVARCHAR(50) NOT NULL, 
	[Gender] NVARCHAR(50) NOT NULL,
	[GuardianMobileNo] NVARCHAR(50) NULL,
	[FormNo] NVARCHAR(50) NULL,
	[EnrollNo] NVARCHAR(50) NULL,
	[MACHINEID] NVARCHAR(50) NULL,
	[PreviousClass] NVARCHAR(50) NULL,
	[PreviousInstituteName] NVARCHAR(250) NULL,
	[YearOfPassing] NVARCHAR(50) NULL,
	[PreviousRollNo] NVARCHAR(50) NULL,
	[PreviousPercent] NVARCHAR(50) NULL,
	[MotherName] NVARCHAR(50) NULL, 
	[DateOfBirth] DATETIME NULL,  
	[Category] NVARCHAR(50) NULL, 
	[AlternateMobileNo] NVARCHAR(50) NULL, 
	[StudentEmail] NVARCHAR(60) NULL,
	[GuardianEmail] NVARCHAR(60) NULL,
	[StudentType] NVARCHAR(50) NULL,
	[Medium] NVARCHAR(50) NULL,
	[Address] NVARCHAR(500) NULL, 
	[CityId] INT NULL,
	[Village] NVARCHAR(60) NULL,
	[StateId] INT NULL,
	[Religion] NVARCHAR(50) NULL,
	[Image] NVARCHAR(350) NULL, 
	[Remarks] NVARCHAR(350) NULL, 
	[IsActive] BIT NULL DEFAULT 0, 
	[IsDelete] BIT NULL DEFAULT 0, 
	[ModifyDate] DATETIME NULL DEFAULT GetDate(), 
	[ModifyBy] INT NULL, 
	[AddedDate] DATETIME NULL DEFAULT GetDate(), 
	[AddedBy] INT NULL,
)
